LeaveTrackingApp/views/leaves_views.py, requirements.txt
added transaction in create leave api. If there is any error encountered in creating leave or creating notification for that leave, we'll rollback the changes and return the error
=> [Fix]: added transaction in create leave api

UserApp/serializers.py, UserApp/views/user_views.py
filtering based on role and dept key rather than id
=> [Refactor]: filtering based on key and added profile image in serializer

UserApp/serializers.py, UserApp/views/user_views.py
modified user list api response format and query pararm format
=> [refactor]: modified user list api

LeaveTrackingApp/serializers.py
modified leave serializer, the user and approver fields now contain name, designation and profile pic too
=> [refactor]: modified leave serializer

LeaveTrackingApp/serializers/__init__.py, LeaveTrackingApp/serializers/holiday_calendar_serializers.py, LeaveTrackingApp/serializers/leave_serializers.py, LeaveTrackingApp/urls.py, LeaveTrackingApp/views/__init__.py, LeaveTrackingApp/views/holiday_calendar_views.py, LeaveTrackingApp/views/leaves_views.py, PushNotificationApp/serializers/__init__.py, PushNotificationApp/serializers/push_notification_serializers.py, PushNotificationApp/urls.py, PushNotificationApp/views/__init__.py, PushNotificationApp/views/push_notification_views.py, UserApp/serializers/__init__.py, UserApp/serializers/role_department_serializers.py, UserApp/serializers/user_serializers.py, UserApp/urls.py, UserApp/views/__init__.py, UserApp/views/authentication_views.py, UserApp/views/role_department_views.py, UserApp/views/user_views.py
Modified folder structure of all apps. 
Created a serializer folder in all apps and created serializer files specific to different models in an app.
Modified leave serializer to have a serializer for creating leave and a separate serializer for retrieving leave details.
=> [WIP][Refactor]: Folder structure modified

LeaveTrackingApp/views/leaves_views.py
modified create leave api to handle the error while pushing notifications.
=> [refactor]: modified create-leave api

LeaveTrackingApp/utils.py, LeaveTrackingApp/views/leaves_views.py
added overlapping leaves validation in create leave api
=> [Refactor]: create leave validation

PushNotificationApp/serializers/__init__.py, PushNotificationApp/serializers/push_notification_serializers.py, PushNotificationApp/urls.py, PushNotificationApp/views/__init__.py, PushNotificationApp/views/push_notification_views.py
Created fetch notifications api which will fetch all notifications where the user is in recievers list of notifications.
=> [Feat]: Created Fetch Notifications API

PushNotificationApp/serializers/push_notification_serializers.py, PushNotificationApp/views/push_notification_views.py
added filtering in fetch Notifications
=> [Refactor]: added filtering in fetch Notifications

UserApp/serializers/__init__.py, UserApp/serializers/user_serializers.py, UserApp/views/user_views.py
modified user apis and added a serializer for showing user profile in app.
=> [Refactor]: modified user get api

LeaveTrackingApp/utils.py
modified util of leave tracking app, a slight change in response format
=> refactor: modified util

LeaveTrackingApp/views/leaves_views.py
modified response format for monthwise unpaid data api
=> [Refactor]: monthwise unpaid api

UserApp/serializers/user_serializers.py
added work_type in user list serializer.
=> [refactor]: modified user list serializer

UserApp/utils.py
replaced 'super-admin' to 'hr' in accessibility to admin panel in sign_in_web function
=> [Fix]: hr access in admin panel

LeaveTrackingApp/views/leaves_views.py
removed send email and push notification functions from transaction block so that they do not hamper leave creation
=> [Fix]: create leave api

LeaveTrackingApp/models.py, LeaveTrackingApp/serializers/calendar_and_policy_serializers.py, LeaveTrackingApp/views/calendar_and_policy_views.py
- modified update calendar and update policy apis to send policy or calendar data in response instead of a message and added some other validations and optimizations.
- refactored serializers
- also can send edited data with sending for approval
=> refactor: modified documents apis, and serializers and model

UserApp/utils.py
added user onboarding status in app sign in response
=> [Refactor]: sign in api

LeaveTrackingApp/views/leaves_views.py, UserApp/views/user_views.py
kept send email in a try except block so that it doesn't send 500 error even when primary functionality is successful, sending success code with errors where send email fails.
=> [Refactor]: apis having send email

UserApp/views/user_views.py
default sorting changed to descending order of created_at
=> [Refactor]: user list default sorting changed

LeaveTrackingApp/utils.py, LeaveTrackingApp/views/leaves_views.py
Fixed bug and optimised db calls in employee attendance api
=> fix: employee attendance data bug

LeaveTrackingApp/serializers/leave_serializers.py
added leave_type_id in leave details serializer required in frontend for mapping.
=> [Refactor]: leave details serializer

PushNotificationApp/serializers/push_notification_serializers.py
added user profile_image key in fetch notification serializer.
=> [Refactor]: notification serializers

LeaveTrackingApp/urls.py, LeaveTrackingApp/views/__init__.py, LeaveTrackingApp/views/temp_view.py
- created api for clearing leaves and day_details
- created api for clearing notifications
=> [Feat]: clear leave data api

LeaveTrackingApp/views/calendar_and_policy_views.py
changed the status code of get leave policy and get holiday calendar api to 200 ok instead of 404 not found, if no data is found.
=> [Fix]: get leave policy status code

UserApp/serializers/user_serializers.py
added email key in user app profile serializer for get user ( by id ) api
=> [Refactor]: add user email in get user api

LeaveTrackingApp/serializers/leave_serializers.py
- integrated the aws s3 storage to upload files related to leaves 
- modified serializers
- modified create leave api to accept content type as form-data too
=> [Feat]: sick leave docs

LeaveTrackingApp/views/calendar_and_policy_views.py
- added notifications in create leave policy and create calendar too (in the case if status is sent as "Sent For Approval").
=> [Refactor]: admin panel notifications

LeaveTrackingApp/views/calendar_and_policy_views.py
changed get policy and get calendar apis (sending empty object if no data found)
=> [Refactor]: get document apis

LeaveTrackingApp/utils.py
fixed the unpaid days calculation if half days are also present
=> fix: unpaid count for half days

LeaveTrackingApp/views/leaves_views.py
- filtered out yearly leave types from get leave type api
=> [Fix]: hide yearly leaves in leave types

LeaveTrackingApp/views/calendar_and_policy_views.py
- sorted the dates in holidays in get holiday api
=> [Fix]: sorted dates in get holiday api

PushNotificationApp/serializers/push_notification_serializers.py
- added created_by key in response of get notifications
=> [Refactor]: add created by in notification api

UserApp/views/user_views.py
- modified create user and bulk user add apis
- if a user is soft deleted and added again, is_deleted becomes false and user's data gets updated with new data
- optimised repeated db calls 
API response message:
=> [refactor]: create user api and bulk user add api changed

UserApp/templates/onboarding_template.html, UserApp/views/user_views.py
- added dummy link in onboarding template
- updated create user api
=> [Chore]: add dummy link in template

LeaveTrackingApp/views/leaves_views.py
- changing the start and end dates of leave based on the days being withdrawn.
=> [Refactor]: withdraw leave api modified

LeaveTrackingApp/views/leaves_views.py
- added optional leave in leave type api
=> fix: added optional leave in leave type api

LeaveTrackingApp/views/leaves_views.py, PushNotificationApp/views/push_notification_views.py, core/settings/base.py
Modified dates of notification description.
=> Modified dates of notification description

LeaveTrackingApp/utils.py
Resolved issue related to error handling in unpaid count of Employee leave in Employee profile.
=> resolved issue related to unpaid count

LeaveTrackingApp/utils.py
Added status to Yearly leave of Users.
=> added status to yearly leaves

LeaveTrackingApp/utils.py
Paternity leave:
1) When applying for paternity leave if total leave count of all paternity leave taken or yet to be taken exceeds 10 then:
2)Already taken all the paternity leave this year:
=> Paternity leave Implementation 

LeaveTrackingApp/views/leaves_views.py
=> added id in unpaid leave displayed to HR

LeaveTrackingApp/views/leaves_views.py
resolved withdraw leave email error
=> resolved withdraw leave email error

LeaveTrackingApp/views/leaves_views.py
=> withdraw email

LeaveTrackingApp/views/leaves_views.py
removed reason from withdraw notification
=> removed reason from withdraw notification

LeaveTrackingApp/views/leaves_views.py, common/urls.py, common/views/__init__.py, common/views/temp_views.py
Added APIs to delete documents.
Leave email updates
=> Backend issues
